insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Domingo', 9, 11, 92, 'moderate rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Segunda-feira', 5, 8, 12, 'light rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Terça-feira', 8, 10, 20, 'moderate rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Quarta-feira', 4, 9, 100, 'heavy intensity rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Quinta-feira', 1, 7, 24, 'ligth rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Sexta-feira', 8, 8, 60, 'moderate rain');
insert into previsao_tempo (nome_dia, temp_minima, temp_maxima, umidade_relativa_ar, descricao) values ('Sábado', 5, 8, 90, 'moderate rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Domingo', 9, 11, 92, 'moderate rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Segunda-feira', 5, 8, 12, 'light rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Terça-feira', 8, 10, 20, 'moderate rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Quarta-feira', 4, 9, 100, 'heavy intensity rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Quinta-feira', 1, 7, 24, 'ligth rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Sexta-feira', 8, 8, 60, 'moderate rain');
--insert into tblPrevisoes (id, nomeDia, tempMinima, tempMaxima, umidadeRelativaAr, descricao) values (default, 'Sábado', 5, 8, 90, 'moderate rain');